---
version: '3'
services:
  crond:
    container_name: travis-cleanup
    build: .
    volumes:
      - ./configuration/clouds.yml:/etc/openstack/clouds.yml:ro
      - ./configuration/secure.yml:/etc/openstack/secure.yml:ro
